### ISSUE TITLE
Follow-up work from browser-engine-system migration

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-tv#1063]
Follow-up from #1039. This is a collection of things that are missing in the first iteration of the migration to `browser-engine-system`. For now I'll just collect everything here and will file separate issues as needed.

### Components 0.21

* [x] ~~Setup tracking protection and make sure toggle behaves correctly~~
* [x] ~~Add interception implementation for firefox:home and other internal pages~~

### Components 0.22

* [x] (https://github.com/mozilla-mobile/android-components/issues/696) "X-Requested-With" header is cleared

### Components 0.23

* [x] (https://github.com/mozilla-mobile/android-components/issues/643) Add fullscreen API behavior 
* [x] (https://github.com/mozilla-mobile/android-components/issues/718) Error pages
* [x] (https://github.com/mozilla-mobile/android-components/issues/728) Call onNavigationStateChange() earlier (Improvement)

### Misc

* [x] Re-add `onFocusChange` behavior: https://github.com/mozilla-mobile/firefox-tv/blob/ec097ab058862129f0b5baa0294983ee32a67ab5/app/src/amazonWebview/java/org/mozilla/focus/webview/FirefoxAmazonWebView.kt#L90-L103
To test this is fixed:
> To test this is fixed:
>  Open YT.com/tv
>  Open menu
>  Close menu
>  move selection
>    expected: selection moves
>    actual: user cannot move selection
* [x] ~~InfoFragment: Do we need to hide the WebView if we are loading an internal page?~~
* [x] ~~InfoFragment: Do we need to re-add to onPageStart():  `progressView.announceForAccessibility(getString(R.string.accessibility_announcement_loading));`~~
* [x] ~~The back/forward state in the toolbar updates very slowly. It looks like you need to move the cursor around to make it refresh at times (?!).~~  (Improved this and filed an a-c issue to improve this).
* [x] Internal pages are now black text on a white background?

### QA

* [x] Make sure EngineView.scrollByClamped performs fast. Consider adding API to EngineView.
* [x] ~~Make sure tracking protection is disabled in InfoFragment (Is that strictly required?)~~
* [X] ~~Make sure back/forward navigation is working properly.~~ Fixed it to behave consistently - but actual behavior is to be defined in # #1071.
* [ ] Make sure handling external URLs (with fallback) are working properly (Do we even support that?)

### Crashes

* [x] ~~STR (Nexus 9): Launch, Click Rotten Tomatoes tile, wait for page to load, press back.~~
```
 E  java.lang.IllegalStateException: No selected session
 E      at mozilla.components.browser.session.SessionManager.getSelectedSessionOrThrow(SessionManager.kt:56)
 E      at mozilla.components.feature.session.SessionUseCases$LoadUrlUseCase.invoke$default(SessionUseCases.kt:27)
 E      at org.mozilla.focus.browser.BrowserFragment.loadUrl(BrowserFragment.kt:280)
 E      at org.mozilla.focus.ScreenController.showBrowserScreenForUrl(ScreenController.kt:92)
 E      at org.mozilla.focus.MainActivity$sessionObserver$1.onNoActiveSession(MainActivity.kt:65)
 E      at org.mozilla.focus.MainActivity$sessionObserver$1.onSessionRemoved(MainActivity.kt:55)
 E      at mozilla.components.browser.session.SessionManager$remove$$inlined$synchronized$lambda$1.invoke(SessionManager.kt:158)
 E      at mozilla.components.browser.session.SessionManager$remove$$inlined$synchronized$lambda$1.invoke(SessionManager.kt:16)
 E      at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:106)
 E      at mozilla.components.browser.session.SessionManager.notifyObservers(SessionManager.kt)
 E      at mozilla.components.browser.session.SessionManager.remove(SessionManager.kt:158)
 E      at mozilla.components.browser.session.SessionManager.remove$default(SessionManager.kt:127)
 E      at org.mozilla.focus.browser.BrowserFragment.onBackPressed(BrowserFragment.kt:270)
 E      at org.mozilla.focus.MainActivity.onBackPressed(MainActivity.kt:154)
 E      at android.app.Activity.onKeyUp(Activity.java:2725)
```

**Comment by pocmo** [comment]
> Make sure EngineView.scrollByClamped performs fast.

Looking at the bytecode and decompiling this back to Java we get:

```
   private static final WebView extractWebView(@NotNull EngineView $receiver) {
      View var10000 = $receiver.asView();
      if (var10000 == null) {
         throw new TypeCastException("null cannot be cast to non-null type android.widget.FrameLayout");
      } else {
         FrameLayout viewGroup = (FrameLayout)var10000;
         var10000 = viewGroup.getChildAt(0);
         if (var10000 == null) {
            throw new TypeCastException("null cannot be cast to non-null type android.webkit.WebView");
         } else {
            return (WebView)var10000;
         }
      }
   }
```

* `asView()` -> Does a cast (see below)
* `null` checks -> No performance problem
* `getChildAt()` -> Does a bounds check and accesses an array -> No performance problem

So the only thing left are casts (EngineView -> View, View -> FrameLayout, View -> WebView). From a bit of searching around it doesn't look like this will be expensive. But as the mapping between never changes between EngineView <-> WebView, we can just cache it.

**Comment by mcomella** [comment]
It looks like most of these items are addressed.

**Comment by mcomella** [comment]
And we haven't been seeing any urgent problems: closing.
