### ISSUE TITLE
Update to Mozilla components 0.23

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/firefox-tv#1076]
Follow-up from #1063: Update to Mozilla components 0.23 once released.

This release will contain:
* [x] (https://github.com/mozilla-mobile/android-components/issues/643) Add fullscreen API behavior 
* [x] (https://github.com/mozilla-mobile/android-components/issues/718) Support for error pages
* [x] (https://github.com/mozilla-mobile/android-components/issues/728) Call onNavigationStateChange() earlier (Improvement)

**Comment by bbinto** [comment]
Let's wait until Friday and decide in the planning meeting to include it in the sprint

**Comment by csadilek** [comment]
Since this upgrade now fixes a P1 issue (https://github.com/mozilla-mobile/firefox-tv/issues/1087), we can also upgrade without bringing in new functionality (just to fix the bug) if it's considered too risky otherwise. Please let us know.

**Comment by AaronMT** [comment]
Will this happen today?

**Comment by liuche** [comment]
Closed with #1114
