### ISSUE TITLE
[META] Organize Homescreen by Channels

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1630]
### Why/User Benefit/User Problem

As a user, I want the tiles on the homescreen to be organized using both up/down arrows and side-to-side so that I can reach my desired tile faster given my FireTV remote.

We also assume that such organization will help users mental model and navigation. Up/Down to change channel, right/left to navigate content of a single channel. Embracing the d-pad navigation will also help users plan an action from point A to point B. 

The titles bring deeper understanding for first time users. It enables them to identify what the content of a channel is about from first launch.

### What / Requirements

Broken into following tickets:
- [x] #2110 
- [ ] #2111 
- [ ] #2112 
- [ ] #2123 UX recs for Alternative to loading, error state (persist recs)
  - [ ] https://github.com/mozilla-mobile/firefox-tv/issues/2154 Source default content
  - [ ] #2186 Persist Pocket recs
  - [ ] #2187 Reduce Pocket foreground fetch interval
  - [ ] #2188 Add background fetch
- [x] #2125 Make sure removing pinned tiles still works
- [ ] #2159 channel follow-up

_When working on these issues: consider if the issues can be broken down further to increase parallelization._

### Design Details

A channel is a scrollable row composed of content cards (aka programs). Programs can have different content types and states.

In the case of "Pinned sites" the content can be a website screenshot or the first letter of the website if screenshot fails (we could explore/test more around screenshots vs favicon vs apple touch icon in the future).

If the program title is too long the text overflows and automatically scrolls when the program is focused.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/1721875/47353651-10928180-d6bd-11e8-9726-939f26011b5a.png">

Channels can have different states:
- default
- focus
- focus + scroll
- edit

The default state displays the channel title plus the channel programs.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/1721875/47354814-fdcd7c00-d6bf-11e8-886c-5dec96823c0f.png">

The focus state is enabled when a program is focused. 

<img width="957" alt="image" src="https://user-images.githubusercontent.com/1721875/47354938-5ac93200-d6c0-11e8-83a3-85a9ed375e52.png">

focus + scroll state: We always focus the program in position 1 until we reach the forth to last program. The focus then moves to position 2 for the third to last, position 3 for the second last and position 4 for the last one.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1721875/47355145-e216a580-d6c0-11e8-9a33-9c9ec15ae135.png">

### Technical Notes (from Mike)

Implementation tip: look into the [leanback support libraries](https://github.com/googlesamples/androidtv-Leanback) to see if there is a re-usable component for channel rows. Maybe `RowFragment` (as a sub-fragment?)?

Resources:
- Getting started (doesn't seem to helpful to dissect support lib components): https://developer.android.com/training/tv/
- Minimal docs in leanback package overview: https://developer.android.com/reference/android/support/v17/leanback/package-summary
- Support lib samples: https://github.com/googlesamples/androidtv-Leanback

I think using the samples might be the best way to figure out how these things work. :hurtrealbad:

**Comment by brampitoyo** [comment]
All the design details that @athomasmoz has outlined are correct.

Amin’s proposal has covered the scenario where 5 tiles are shown on the screen at one time (plus half-tiles on its left and right):

<img src="https://user-images.githubusercontent.com/51007/56935604-3d30c580-6b46-11e9-92ca-1ba4e5d95b60.png">

This proposal is good and doesn’t need to be rethought. We just need to expand it. Why?

1. In the future, we might accommodate video content and want bigger tile sizes
2. In the future, we might have so many channels, that we need a sidebar to serve as navigation aid
3. In the future, we might have many tiles that list playable media; they need to look cinematic and inviting

## 1. Expanded system should accommodate rows of many different sizes:

It’s prudent to keep Amin’s initial tile size – 150x84px – as a baseline. This size can show 5 tiles at a time (plus half-tiles on the left and right).

To future-proof it, we also want 4, 3, 2 and maybe even 1-tile rows. But we still want to keep the padding-between-tiles consistent.

What should the sizes of these rows be?

![grid-system-1@2x](https://user-images.githubusercontent.com/51007/56935732-263ea300-6b47-11e9-80be-71799fa3ea0b.png)

By using these sizes:

* The padding between tiles will stay consistent at 24px, no matter the row size
* We will always have a space to show half-tiles on either sides, no matter the row size
* The last program before half-tiles will always line up, no matter the row size

## 2. Expanded system should accommodate a sidebar

We don’t have a sidebar today, but we might have one in the future. To future-proof our current design, we need a system that can easily accommodate a sidebar.

Thankfully, no further change is necessary. Note that our current design has a side padding of 57px:

![grid-system@2x](https://user-images.githubusercontent.com/51007/56936844-b2ec5f80-6b4d-11e9-8103-78af92d5597f.png)

This is enough space for a minimised sidebar that’s 33px wide, with a 24px padding-between:

![grid-system-1@2x](https://user-images.githubusercontent.com/51007/56936850-b849aa00-6b4d-11e9-925a-fd8868f6dd9d.png)

And when the sidebar is maximised to 270px wide, we can keep the 24px padding-between values without causing any problem to the rest of the layout:

![grid-system-2@2x](https://user-images.githubusercontent.com/51007/56936862-c8618980-6b4d-11e9-9517-b6eee15b41bd.png)

## 3. Expanded system should look and feel cinematic

### 3a. Tiles should be readable without words

We were originally planning to have titles below our tiles:

<img src="https://user-images.githubusercontent.com/51007/56935604-3d30c580-6b46-11e9-92ca-1ba4e5d95b60.png">

To future-proof it, we want to make the tiles themselves more readable by showing site logo/logotype, instead of relying on titles underneath.

Note: it’s still very important to have `alt` value for each tile, so Android Talkback is able to read it aloud.

![Phase 5 - minimised (search)@2x](https://user-images.githubusercontent.com/51007/56936958-6ce3cb80-6b4e-11e9-925b-6df18784a4d2.png)

### 3b. Active channels should clearly be distinguished

Currently, a tile can either be:

1. Focused: has blue ring
2. Not focused: no blue ring

<img src="https://user-images.githubusercontent.com/1721875/47354814-fdcd7c00-d6bf-11e8-886c-5dec96823c0f.png">

<img src="https://user-images.githubusercontent.com/1721875/47354938-5ac93200-d6c0-11e8-83a3-85a9ed375e52.png">

To future-proof it, we want to make all inactive channels look faded out.

The formula is pretty simple:

1. Draw a box overlaying each tile in the inactive channel
2. Give it a value of `grey-90` 60%

![grid-system-1@2x](https://user-images.githubusercontent.com/51007/56937447-cea53500-6b50-11e9-974f-010519213f63.png)

That covers my proposal of expanding the system without changing our current proposal too much.

What do you think?

**Comment by athomasmoz** [comment]
Thanks @brampitoyo , that looks great! 
* What parts of this expanded vision do you see as MVP (if any)?
* For 3a, I love how clear the tiles are. I was thinking about edge cases.. what should this look like for user pinned tiles? Will we be able to get a site logo like that for any site? And what happens if the user pins two pages from the same site (ie. global/sports and global/live)

**Comment by mcomella** [comment]
Thanks Bram! These designs all seem reasonable to me and (hopefully) not too challenging to accommodate! A few questions/thoughts:
- "In the future, we might accommodate video content and want bigger tile sizes". What do you mean by "video content"? Will the tiles just having playing videos inside of them?
- When sidebars expand normally, they overlap the content. In item 2, instead it looks like the content unconventionally translates to the right to make room for the expanded sidebar: is that correct? 
- In #784, Tif discussed increasing the size of the focused tile (i.e. "zooming") to make it more apparent what's focused: is that something we still care about?

**Comment by brampitoyo** [comment]
@athomasmoz wrote:
> What parts of this expanded vision do you see as MVP (if any)?

For MVP, two features are important:

1. Home screen has channels across a wide range of categories
2. Each channel contains popular video sites

They’re both not in this expanded vision.

Two features in the expanded vision are nice to have:
1. Cinematic tiles
2. Faded out inactive channels are both nice to have

(3. “Zoomed” focused tile)

@mcomella wrote:
> In #784, Tif discussed increasing the size of the focused tile (i.e. "zooming") to make it more apparent what's focused: is that something we still care about?

Do you have any input on how to do this easily? I’d be happy if we can use the scaling value used on Fire TV OS homescreen.

And two features aren’t immediately important:
1. Rows with different sizes: only important when we decide to show video preview.
2. Sidebar: only important when we have so many categories, that it’s hard to get an overview without scrolling a lot.

---

@athomasmoz wrote:
> For 3a, I love how clear the tiles are. I was thinking about edge cases.. what should this look like for user pinned tiles? Will we be able to get a site logo like that for any site? And what happens if the user pins two pages from the same site (ie. global/sports and global/live)

Actually, this isn’t an edge case. Users can bookmark any page on the internet, and there’s no way for us to fetch high resolution logo for each site.

So I wonder if we should take this approach:

1. If a pinned tile has been selected/pre-populated by us, then we will give it the cinematic treatment
2. If a pinned tile is user-created, then we will take a screenshot of the page, and give it a title
3. All other channels are pre-populated by us, so they will get the cinematic treatment

![Phase 6 - minimised (pinned sites)@2x](https://user-images.githubusercontent.com/51007/57002701-6704ed80-6c15-11e9-9c9e-bafea21ad11c.png)

---

@mcomella wrote:
> What do you mean by "video content"?

It means that some tiles will directly link to the video (ie. it will open a video player), instead of web pages that lists videos.

These tiles need to be descriptive. For example: its publication and video title should be shown, and there should be enough space to accommodate the video duration. For these reasons, the tiles may need to be larger than the normal size.

![Phase 5 - minimised (pocket)@2x](https://user-images.githubusercontent.com/51007/57002885-b697e900-6c16-11e9-9b59-6aa6c8f4670c.png)

---

@mcomella wrote:
> When sidebars expand normally, they overlap the content. In item 2, instead it looks like the content unconventionally translates to the right to make room for the expanded sidebar: is that correct?

That’s correct. In Android TV, the sidebar doesn’t overlap the content. Instead, it pushes the content to the right.

<img src="https://designguidelines.withgoogle.com/android-tv/assets/0B56kA3exHMkQUlpudWVxam1UYTQ/app-structure-browse-02.jpg">
<img src="https://designguidelines.withgoogle.com/android-tv/assets/0B56kA3exHMkQVVA0Ym4yeU1pTEE/app-structure-browse-01.jpg">

**Comment by mcomella** [comment]
> > In #784, Tif discussed increasing the size of the focused tile (i.e. "zooming") to make it more apparent what's focused: is that something we still care about?
> 
> Do you have any input on how to do this easily? I’d be happy if we can use the scaling value used on Fire TV OS homescreen.

Yep! We're doing this on the pocket screen right now. We just specify a scale multiplier like so: https://github.com/mozilla-mobile/firefox-tv/blob/9066aabab817742a67702fc7c1ba94a0f9ca9998/app/src/main/res/animator/pocket_video_item.xml#L9-L13

As for getting the scale value from the Fire OS homescreen, I think we'll have to calculate that ourselves (e.g. by taking screenshots and measuring).

**Comment by mcomella** [comment]
> > Do you have any input on how to do this easily? I’d be happy if we can use the scaling value used on Fire TV OS homescreen.
> 
> Yep! We're doing this on the pocket screen right now. We just specify a scale multiplier like so:

I spoke with Bram: we should use this multiplier (1.05) on our homescreen.

**Comment by liuche** [comment]
@athomasmoz this doesn't look like it's immediately actionable for the MVP, but this should be broken up into individual bugs. Let us know if we can help.

**Comment by athomasmoz** [comment]
Yep, I'll break out those additional pieces into new stories.
