### ISSUE TITLE
[Meta] Follow-ups for Overlay re-architecture

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1644]
Keeping track of some comments/follow-ups to break out from #1637:
- [ ] Be explicit about startup flow (between Intents, restoring instance, onCreate) https://github.com/mozilla-mobile/firefox-tv/pull/1637#discussion_r245436918 #1658
- [ ] Use `onSaveInstanceState` for restoration, in a way that doesn't break "Clear Data" (also consider fixing Clear Data to not need activity recreation) https://github.com/mozilla-mobile/firefox-tv/pull/1637#discussion_r245187268 #1659
- [x] Can't exit w/ back on urls opened from VIEW intent (or any intent)  #1638
- [ ] #1632 switch to a-c SafeIntent
- [ ] #1638 Improve about:home handling
- [ ] Going back from Pocket or Settings, will not refocus the previous button #1660
- [X] Youtube focus - Open two pocket videos
- [ ] after ac37, check if back/forward buttons still toggle on/off indefinitely (no clear STR) #1661
- [ ] Move Action.Show*Toast to consumable https://github.com/mozilla-mobile/firefox-tv/pull/1637#discussion_r245857132
- [ ] Does switching from LinearLayout to FrameLayout w/ Fragment containers cause any perf regressions? https://github.com/mozilla-mobile/firefox-tv/pull/1637#discussion_r245149464 #1661
- [ ] Add helper function to throw illegal states in a Sentry.capture(Throwable) #1662
- [ ] Verify Telemetry is still working #1661

**Comment by liuche** [comment]
Filed individual bugs and linked to these in the first comment.

**Comment by mcomella** [comment]
The individual bugs are filed: the meta is not serving any purpose.
