### ISSUE TITLE
Generic channel follow-up

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2159]
### Vision statement / What / Requirements
This is a follow up bug for completing tasks that were left undone (or broken) by #2110.
##### High Priority
- [x] Telemetry for pinned/bundled tile clicks https://github.com/mozilla-mobile/firefox-tv/issues/2162
- [x] Telemetry for removing tiles https://github.com/mozilla-mobile/firefox-tv/issues/2162
- [x] Focus lost when scrolling right all the way off the end of the tiles (only on first try?) https://github.com/mozilla-mobile/firefox-tv/issues/2163
- [ ] Handle deleting items from channels (works for pinned tiles, won't for other channels) (Double check with UX. This may not be required) https://github.com/mozilla-mobile/firefox-tv/issues/2166
- [ ] Picasso in `BundledPinnedTile#toChannelTile` loads `"file:///android_asset/bundled/$imagePath"`.  Find a safer approach https://github.com/mozilla-mobile/firefox-tv/issues/2164

##### Medium Priority
- [ ] `FocusRepo` needs to know about non-empty channels (`navUrlInput#nextFocusDown` needs to be the first non-empty channel). Find a good approach https://github.com/mozilla-mobile/firefox-tv/issues/2165

##### Low Priority
- [ ] UUID vs String for tile types (Custom/Bundle use different IDs) https://github.com/mozilla-mobile/firefox-tv/issues/2167
- [ ] Clean up: expand unified `ChannelTile` type, then remove `BundledPinnedTile` and `CustomPinnedTile` https://github.com/mozilla-mobile/firefox-tv/issues/2168
- [x] ~In the previous implementation, `onBindViewHolder` set different padding to bundled vs custom tiles.  Find out how to handle this case when they're all the same type~ (cleaning up tile styling will be part of https://github.com/mozilla-mobile/firefox-tv/issues/2112)

##### Unprioritized
- [ ] Channels are currently added to a `LinearLayout`.  Change this to a vertical `RecyclerView`, in case we need to take advantage of any of its animations or performance optimizations later https://github.com/mozilla-mobile/firefox-tv/issues/2169

**Comment by mcomella** [comment]
Bugs are filed for the individual issues so I don't think there's value in this untracked meta: closing. @Baron-Severin, if you disagree, please reopen.
