### ISSUE TITLE
Fetch & Save Pocket Articles at Regular Intervals

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2223]
### Why/User Benefit/User Problem

As a user, I want Pocket content to be updated regularly, so that I can find new videos to watch when I open Firefox

### Tasks

* Confirm increased cost with Pocket for fetching data for all users nightly
* Get default content from Pocket
* Either turn off foreground fetching of new articles and close #2187 , or ensure #2187 has been prioritized for a future sprint

### Acceptance Criteria (how do I know when I’m done?)

* A list of Pocket videos is available to the user every time they open the app
  * The first time a user opens Firefox, a default list of Pocket videos are displayed
  * Each day a user opens Firefox, new Pocket content is displayed
  * Fetching new data should happen at night, when user is least likely to be using the app (e.g. because they're sleeping; Bram guessed 3am-5am their time zone but we should double-check that)
* Pocket content is fetched & saved regularly, so that users do not need to wait for it when the app opens
  * Fetching content does not occur at the same time for all users, to avoid overloading (add randomness to scheduled times, back-off times; consider WorkManager)
  * Pinging Pocket's server nightly for each user does not drastically increase the cost

### Follow-ups
- [x] Close #2297 (videos update when user looks at them) if applicable
- [x] Close #2187 (foreground fetch interval) if applicable
- [x] Close #2261 (fetching for inactive users) if applicable
- [ ] See if there are any other issues to close

**Comment by athomasmoz** [comment]
@athomasmoz to tackle conversations with Pocket on additional API calls

**Comment by mcomella** [comment]
@brampitoyo It turns out the Android APIs don't make it easy to guarantee a task daily at specific time (e.g. 3am) or within specific hours (e.g. 3am - 5am). For the MVP, can we say we'll make a best effort attempt to update within those hours but only guarantee we'll update once per day?

fwiw, by "best effort", in our testing, the system defaults to updating within seconds of the time we specify but may not guarantee it will continue to do so forever.

Note to self: we may want to add telemetry to track whether this solution is good enough or not.

**Comment by brampitoyo** [comment]
> …can we say we'll make a best effort attempt to update within those hours but only guarantee we'll update once per day?

That works for me. A once-a-day update is a good minimum, especially considering the fact that Pocket doesn’t update its video recommendations as often as they do with articles.

**Comment by liuche** [comment]
Follow-ups filed, can close.
