### ISSUE TITLE
Releng checklist - v3.10 (take 2)

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#2338]
##### Sprint Release Owner: @mcomella 
 _Since last sprint we did not release v3.10, name these LAT's as 3.10-LAT3 and 3.10-LAT4_
#### Tuesday # 1

- [x] Upgrade a-c

#### Wednesday # 1

- [x] Export strings (*if applicable*) ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Localization#exporting-strings-for-translation))
  - Submitted https://github.com/mozilla-l10n/firefoxtv-l10n/pull/25
- [x] Create PR for bumping version (`X.X-LAT1`)
  - Merge to master
- [x] Cut LAT branch `releases/vX.X-LAT1`
- [x] Create GitHub pre-release build `vX.X-LAT1`([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Releng-Checklist#final-builds))
- [x] Release LAT ([instructions](https://developer.amazon.com/docs/app-testing/live-app-testing-getting-started.html))

#### Wednesday # 2 (soft code freeze)

- [x] Create PR for bumping version (`X.X-LAT2`)
  - Merge to master
- [x] Cut LAT branch `releases/vX.X-LAT2`
- [x] Create GitHub pre-release build `vX.X-LAT2` ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Releng-Checklist#final-builds))
- [x] Release LAT ([instructions](https://developer.amazon.com/docs/app-testing/live-app-testing-getting-started.html))

#### Thursday # 2

- [x] [QA] run screenshot test and upload ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Localization#screenshots))
- [x] Upgrade a-c on master

#### Friday # 2 (hard code freeze)

- [x] [Product, QA, eng] sign-off for release

#### Monday # 3

- [x] Create PR for bumping version (`X.X`) and updating changelog
  - Update the CHANGELOG: glance over the changelog to see if any major
    features are missing and add the new release header (don't forget to add the diff links at the bottom)
  - Merge to master
- [x] Cut release branch `releases/vX.X`
- [x] Create GitHub release build `vX.X`([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Releng-Checklist#final-builds))
- [x] Submit app with staged rollout at 1% ([instructions](https://developer.amazon.com/docs/app-submission/submitting-apps-to-amazon-appstore.html))

#### Tuesday # 3

- [x] [QA] sign-off
- [x] Bump rollout to 20%

#### Wednesday # 3
_mcomella is out-of-office: I requested liuche to complete this task_
- [x] [QA] sign-off
- [x] Bump rollout to 100%

**Comment by mcomella** [comment]
afaik, liuche rolled out to 100%.
