### ISSUE TITLE
Release management checklist - v3.11

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2402]
_Note: previous versions of this ticket were called, "Releng checklist - vX.X"._

##### Sprint Release Owner: @Baron-Severin
Some items are crossed out as this is a shortened sprint (1 week only)

_Think something can be automated? Add it to [this doc](https://docs.google.com/document/d/1I_pf7RhR8uC0P_jB8o5Y8teNxUuLlpKiF_FyBW9veFY/edit?ts=5cdc4d67)._

#### Tuesday # 1

- [x] Upgrade a-c

#### Wednesday # 1

- [x] Export strings (*if applicable*) ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Localization#exporting-strings-for-translation))
- [x] Create PR for bumping version (`X.X-LAT1`)
  - Merge to master
- [x] Cut LAT branch `releases/vX.X-LAT1`
- [x] Create GitHub pre-release build `vX.X-LAT1`([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#final-builds))
- [x] Release LAT ([instructions](https://developer.amazon.com/docs/app-testing/live-app-testing-getting-started.html))
  - [x] Email team announcing release ([template/instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))

#### ~Wednesday # 2 (soft code freeze = noon PT)~

- [ ] ~Create PR for bumping version (`X.X-LAT2`)~
  - ~Merge to master~
- [ ] ~Cut LAT branch `releases/vX.X-LAT2`~
- [ ] ~Create GitHub pre-release build `vX.X-LAT2` ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#final-builds))~
- [ ] ~Release LAT ([instructions](https://developer.amazon.com/docs/app-testing/live-app-testing-getting-started.html))~
  - [ ] ~Email team announcing release ([template/instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))~

#### Thursday # 2

- [ ] [QA] run screenshot test and upload ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Localization#screenshots))
- [ ] ~Upgrade a-c on master~
- [x] File new Release Management checklist with next version and add to top of Backlog

#### Friday # 2 (hard code freeze)

- [ ] [Product, QA, eng] sign-off for release

#### Monday # 3

- [x] Create PR for bumping version (`X.X`) and updating changelog
  - Update the CHANGELOG: glance over the changelog to see if any major
    features are missing and add the new release header (don't forget to add the diff links at the bottom)
  - Merge to master
- [x] Cut release branch `releases/vX.X`
- [x] Create GitHub release build `vX.X`([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#final-builds))
- [x] Submit app with staged rollout at 1% ([instructions](https://developer.amazon.com/docs/app-submission/submitting-apps-to-amazon-appstore.html))
  - [x] Email team announcing release ([template/instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))

#### Tuesday # 3

- [x] [QA] sign-off
- [x] Bump rollout to 20%
  - [x] Email team announcing release ([template/instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))

#### Wednesday # 3

- [x] [QA] sign-off
- [x] Bump rollout to 100%
  - [x] Email team announcing release ([template/instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))
