### ISSUE TITLE
Make Sidebar for switching between states (Home, Settings, Browse)

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#26]
- [x] #62: Add non functional drawer
- [x] Add home button functionality (mcomella)
- [x] Add settings button functionality (bryan)
- [x] Explore ease of adding the website navigation (emily) #70
- [x] Add mini-bar (mcomella) #76

Based on mocks from @lime124
