### ISSUE TITLE
Release management checklist - v4.6

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2900]
# Sprint Release Owner: mcomella

_Think something can be automated? Add it to [this doc](https://docs.google.com/document/d/1I_pf7RhR8uC0P_jB8o5Y8teNxUuLlpKiF_FyBW9veFY/edit?ts=5cdc4d67)._

#### Thursday # 1 (soft code freeze = EoD PT)

- [x] Verify all `strings-ready` issues in Sprint have strings landed (exports now happen automatically). If not, check with L10N/PM if the issue needs to be removed from Sprint.
  - No strings need to land
- [x] Create PR for bumping version (`X.X-LAT1`)
  - Merge to master
- [x] Cut LAT branch `releases/vX.X-LAT1` (this must include a-c upgrade)
- [x] Create GitHub pre-release build `vX.X-LAT1`([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#final-builds))
- [x] Release LAT ([instructions](https://developer.amazon.com/docs/app-testing/live-app-testing-getting-started.html))
  - [x] Email team announcing release ([template/instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))
- [ ] [QA] run screenshot test and upload ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Localization#screenshots))
  - Is this the correct date?

#### Friday # 1 (hard code freeze)
- [x] [Product, QA, eng] sign-off for release
- [x] File new Release Management checklist with next version and add to top of Backlog

#### Monday # 2
- [x] Create PR for bumping version (`X.X`) and updating changelog
  - Update the CHANGELOG: glance over the changelog to see if any major
    features are missing and add the new release header (don't forget to add the diff links at the bottom)
  - Merge to master
- [x] Cut release branch `releases/vX.X`
- [x] Create GitHub release build `vX.X`([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#final-builds))
- [x] Submit app with staged rollout at 1% ([instructions](https://developer.amazon.com/docs/app-submission/submitting-apps-to-amazon-appstore.html))
  - [x] Email team announcing release ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))

#### Tuesday # 2

- [x] [QA] sign-off
- [x] Bump rollout to 20%
  - [x] Email team announcing release ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))

#### Wednesday # 2

- [ ] [QA] sign-off
- [ ] Bump rollout to 100%
  - [ ] Email team announcing release ([instructions](https://github.com/mozilla-mobile/firefox-tv/wiki/Release-Management-Checklist#release-announcement-emails))

**Comment by mcomella** [comment]
Filed new RelMan ticket: https://github.com/mozilla-mobile/firefox-tv/issues/2968

**Comment by mcomella** [comment]
We rolled out to 100%. There's a crash bug we should keep an eye on – https://github.com/mozilla-mobile/firefox-tv/issues/2971 – but don't think is worth spending time on right now. As such, closing ticket.
