### ISSUE TITLE
[meta][telemetry] Improve Telemetry to understand users better

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#319]
Some probes we should add in one of the next releases:

## How do people start and finish their task?
- [x] #323: url bar
    - Typed in search query (www....)
    - Typed in keywords (plain text)
- [x] #324: Clicked tile (top sites) (don't track which tile)

## Navigation
- [x] #325: Drawer nav
    - Clicked home button
    - Clicked back button
    - Clicked forward button
- [x] #326: Used autocomplete suggestion (without typing in the URL fully
- [x] #354: menu sidebar opened/closed

## Setup / do people use tracking protection (after/for 1.1)
- [x] #329: Tracking protection
    - Setting on/off by default
    - Switch to on or off
- [x] #328: Clear cookies etc clicked (via Settings page)

## Documentation
- [x] #327: (maybe not in v1.1?) Core ping
- [x] #341: ^ New UI probes

**Comment by mcomella** [comment]
@bbinto For "search query" vs. "keywoard", do you mean "search query" (how do I tie my shoes?) vs. url (google.com)?

**Comment by mcomella** [comment]
Note that we should document these probes somewhere like: https://github.com/mozilla-mobile/focus-android/wiki/Telemetry

**Comment by Sdaswani** [comment]
Yes these all need data peer review by @liuche too.

**Comment by mcomella** [comment]
@bbinto If we implement this now, we may have to reimplement some of this when later, when we refactor – do we still want to proceed?

**Comment by bbinto** [comment]
agreeing witih @Sdaswani -- let's still add it.

> @bbinto For "search query" vs. "keywoard", do you mean "search query" (how do I tie my shoes?) vs. url (google.com)?

Correct :)

**Comment by mcomella** [comment]
Meta complete; removing from milestone so we don't miscategorize as work.
