### ISSUE TITLE
[meta][refactor] CI

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#392]
- [x] #390: BB PRs and master
- [x] #395 : Port Taskcluster from Focus Android
- [x] #396 : Fix problems from static analysis tools
- [x] #42: Enable proguard
- [x] #465: Add Taskcluster status to README
- TODO

**Comment by mcomella** [comment]
@bkmunar Can you file `P5` `help wanted` follow-up bugs for the static analysis tools you weren't able to add? Thanks!
