### ISSUE TITLE
[meta][refactor] Tests

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#416]
- [x] Get unit tests working (fixed with #390?)
- [x] #447 Rm unused UI tests
- [ ] #438  Loading page UI test
- [ ] #437 UI tests based on new UI

**Comment by Sdaswani** [comment]
+2 ok that second check box!

**Comment by mcomella** [comment]
Blocked on 2.0 tests.

**Comment by mcomella** [comment]
All depending bugs done.
