### ISSUE TITLE
[meta] Navigation Overlay

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#433]
**IA**: 
<img width="710" alt="screen shot 2018-02-16 at 9 59 00 am" src="https://user-images.githubusercontent.com/287322/36321843-163845ba-1300-11e8-9d17-9ad3c3f7a841.png">

**Updated Mocks:**
![nav overlay](https://user-images.githubusercontent.com/287322/36320960-f7c38bb0-12fc-11e8-8720-41ac5dcaef6b.png)
![overlay - toast](https://user-images.githubusercontent.com/287322/36320961-f7da87f2-12fc-11e8-809c-2be67b833b47.png)
Comments - tapping the pin toggle on/off shows the appropriate toast. I'm not sure what toasts look like exactly on TV (I couldn't find one) but according to the guidelines they are possible.

**Assets/Icons**
Ping tif for pinning and updated turbo svgs (can't post to GH).

**Checklist**
- [x] #332 Port navigation functionality out of drawer
- [x] #444 Move navigation to overlay
- [x] #446 Add "Settings" button to Home screen
- [x] #287 Add progress bar
- [x] #459 UX feedback on overlay
- [x] #477 Add enabled/selected/etc state for Overlay buttons
- [x] #502 Hide overlay after url/search entry
- [x] #513 Add "close" hint and logo

**Comment by liuche** [comment]
@lime124 to add mocks to this and other metas

**Comment by lime124** [comment]
![ia](https://user-images.githubusercontent.com/287322/35651669-62c16a5a-0695-11e8-86d9-f227c3ecc78f.png)

**Comment by liuche** [comment]
Closing this now that all the large list items are closed - polish may be done in the last 2 days, but doesn't need to block this meta.

**Comment by mcomella** [comment]
@bbinto Did you mean to reopen this? Maybe it was a side effect of adding, `Epic`?

**Comment by bbinto** [comment]
oh...yeah, that wasn't intentional, will close it again
