### ISSUE TITLE
[meta] Custom Tiles v1

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#434]
For the v1, we will just use the existing Home Screen.

- [x] #440 Load default tiles from config instead of hard-coding
- [x] #441 Add 'pinning' to Navigation Overlay and save pinned site, load to home screen
- [x] #533 Show default tiles as "pinned" and allow unpinning
- [ ] #443 Allow deleting existing home tiles and new tiles
- [ ] #490 Telemetry (# of tiles, pinning/unpinning, visiting custom tile)
- [x] #511 Titles for custom tiles
- [x] #521 Screenshots for tiles

**Comment by liuche** [comment]
Assigning to @lime124 for interaction mocks (mainly deletion, long-press/falafel?)

**Comment by lime124** [comment]
i think this is covered by the nav overlay bug and the pinning bug.

**Comment by mcomella** [comment]
All our custom tiles bugs are being tracked in the milestone so I don't think this meta bug is useful anymore: closing.

**Comment by mcomella** [comment]
@liuche Why is this labelled SUMO? Should it be in the milestone so SUMO doesn't miss this?

**Comment by Sdaswani** [comment]
I think it was in the milestone with SUMO label to remind Joni we needed a SUMO article, but we can also create a specific ticket for that.

**Comment by mcomella** [comment]
Filed https://github.com/mozilla-mobile/firefox-tv/issues/595
