### ISSUE TITLE
[Beta + UX Feedback] Live App Test

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#515]
@lime124 suggested having a single place where people testing our Live App Test version can provide feedback, which is a great idea!

This will be for the Live App Test version that includes 1) progress bar, 2) button states in the overlay.

Please leave all feedback, bugs, issues in a comment and we can collect and gather and open separate issues if needed. Thanks!

**Live App Testing 1.4.0.1**
Nav Overlay
- [x] better colors for navigation overlay button states - this is fixed except for active state #564 
- [x] artifacting in settings gear icon
- [x] #543 text box doesn't need a cursor, should be treated more like a button
- [ ] #528 The turbo mode button should be implemented as a checkbox (discussed with @lime124)

**Live App Testing 1.4.0.2**
General
- [ ] #640 photon white should be tv white #eeeeee. [ux polish]
  - I think this applies to the text and the icons in the overlay.
  - the cursor in the search box on the homescreen
  - the background of the home tiles?
  - svg files also use FFFFFF

Homescreen #641
- [ ] no press state on settings button on the homescreen [ux polish]
* This looks different on the Stick (android 22) and the Square (android 25)
- [ ] the press state is weird on a tile - this is specifically about the color of the "menu" hint [ux polish]

Browser View #642
- [ ] the elevation doesn't seem to be getting applied to the progress bar [ux polish]
- [ ] progress bar is distracting from the rest of the page b/c it's too bright and attention getting [ux polish]
  - things to try for ux first: truncate URL so box just jump around in width, change opacity of box (85-90%), change opacity of gif (or perhaps change opacity of the whole progress bar)

Overlay
- [x]  #549 @bbinto: I expected clicking left on the remote on Home icon should bring you up to the first row (to select TB icon)
- [ ] #592 overscan impacts UI in overlay and progress bar

Button alignment in overlay (see image below in comments) #643
- [x] button_border doesn't seem to be applied to the URL button
- [x] button_border should be updated to photon grey 40
- [x] button_default should be inkTV color and button_disabled (is this an android behaviour?) should be 30% of the default
- [x] does button_pressed have an android default behaviour (i.e. android auto darkens the focus color a bit) otherwise photon blue 60 should do the trick
- [x] the focus state for the circle buttons seems different than the URL button. both should be photon blue 50

Navigation
- [ ] #589 @bbinto: 1) click into Settings from browser overlay 2) clicking the back button on the remote, IMO, should go back to the greyed overlay, however it's reloading the page without overlay

**Comment by eeejay** [comment]
Hey! Some VoiceView feedback, may have more on Monday.

- [ ] In settings->about, the content (version number) is not accessible.
- [ ] The turbo mode button should be implemented as a checkbox (discussed with @lime124)

**Comment by Sdaswani** [comment]
Thanks @eeejay - it would also be nice to understand if these are blockers to shipping, in your opinion.

**Comment by eeejay** [comment]
>  it would also be nice to understand if these are blockers to shipping, in your opinion.

The turbo button is a blocker, imo. i'm mixed about the about page.

**Comment by Sdaswani** [comment]
@eeejay created https://github.com/mozilla-mobile/firefox-tv/issues/528, we may have to ship it in a dot release after 2.1 depending on where we are on our current 2.0 work.

**Comment by Sdaswani** [comment]
I think this is a bug @liuche 

STR:
1. Launch FFTV
2. Youtbue something
3. Open overlay
4. Press 4-way D-pad all the way down

Expected Result: Home button should stay highlighted

Actual Result: Nothing is highlighted, until you press right, and then the settings button is highlight

**Comment by Sdaswani** [comment]
File https://github.com/mozilla-mobile/firefox-tv/issues/549 for https://github.com/mozilla-mobile/firefox-tv/issues/515#issuecomment-369139894

**Comment by Sdaswani** [comment]
Found some bugs with 4.0.2:

- [ ] https://github.com/mozilla-mobile/firefox-tv/issues/571
- [ ] https://github.com/mozilla-mobile/firefox-tv/issues/572
- [ ] https://github.com/mozilla-mobile/firefox-tv/issues/573

**Comment by Sdaswani** [comment]
Found some more bugs:

- [ ] https://github.com/mozilla-mobile/firefox-tv/issues/585
- [ ] https://github.com/mozilla-mobile/firefox-tv/issues/586
- [ ] https://github.com/mozilla-mobile/firefox-tv/issues/587

**Comment by lime124** [comment]
![button states](https://user-images.githubusercontent.com/287322/37064538-32c7176e-2152-11e8-8957-fd11f483f067.png)

**Comment by Sdaswani** [comment]
1.4.0.4 is working pretty good!

**Comment by mcomella** [comment]
@lime124 I find this bug makes it hard for us to split up work so I filed bugs for all the existing issues I could find. Please close this (so nothing more gets added to it) if you think other issues cover all the work here!

**Comment by lime124** [comment]
@mcomella - i 100% agree! @liuche and i were talking about this yesterday. even if it's a super small thing we should open a ticket just so it can be easily tracked and closed. thanks for opening issues for these nits!

**Comment by mcomella** [comment]
We'll leave this in the milestone because it tracks some polish work that was done in this ticket.
