### ISSUE TITLE
[meta] Amazon Fixes

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#755]
These issues should be fixed by April 10th! Maybe we can get these fixed in 2.1.

- [x] https://github.com/mozilla-mobile/firefox-tv/issues/507
- [x] https://github.com/mozilla-mobile/firefox-tv/issues/756
- [ ] https://github.com/mozilla-mobile/firefox-tv/issues/783

**Comment by Sdaswani** [comment]
@AaronMT the two completed tickets are QA ready, and it would be great if you could get us a crash reprot for 783.

**Comment by liuche** [comment]
Bumped #783 back to triage because blocked on Amazon, so won't ship with 2.1.
