### ISSUE TITLE
UX/Copy to finalize strings

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#829]
Ideal deadline: End of week (Friday 4/20) or Monday (4/23)
to give enough time to export strings to L10N + localization

- [x] @aminalhazwani Accessibility strings: Are there any places in the app that need accessibility "hint" strings (that would be focused with a screen reader)? Can you figure these out for @BrianNJones so we can get strings written?
- [x] Finalize strings between UX and Copy
- [x] Add final strings to the UX deliverable first comment #759
- [x] Missing error states & copy? https://github.com/mozilla-mobile/firefox-tv/issues/829#issuecomment-384472711
- [x] @mcomella to do a string import and export, Wed Apr 25 at the latest and ping @Delphine about the export. *edit*: export: https://github.com/mozilla-l10n/firefoxtv-l10n/pull/6 import: https://github.com/mozilla-mobile/firefox-tv/pull/858
 - [x] ~~@AaronMT export screenshots (to L10N/@Delphine)~~ Moved to #868.

**Comment by Delphine** [comment]
@liuche: Thanks for filing this. Do you think you could add a check-box for generating screenshots (which implies importing most recent strings right before generating them) in this list? I'm unsure of the rest of the timeline but basically a good moment to get them would be like a few days before the final string import on your side.

**Comment by aminalhazwani** [comment]
hey @liuche thanks for filing the issue. I will use `code` for the a11y strings.

### Homescreen

**Pocket mega tile focused**
- `Video recommendation by Pocket`
- `Button`

_Example_

![homescreen pocket tile focused](https://user-images.githubusercontent.com/1721875/38987386-d735b23e-43cf-11e8-9ea5-30739e96aa80.jpg)

- `Video recommendation by Pocket`
- `Button`

### Pocket Feed

**Pocket feed, first card focused**
- `Recommended videos` 
_read_ this only for the first card
- `{Title}`
- `Source {Source}`
- `1 of {n}`
- `Link` 
Should we say that this is a link? What's the practice here? While using the Fire TV with VoiceView enabled I heard only `Button` and never `Link`

When VoiceView is enabled the menu button ☰ will provide further spoken feedback. If pressed while a  card is focused:

- `Use left and right to move between items`
How should we call the items? `Items`, `Cards`, or `Recommendations`, or `Recommended videos`. Ideas? 

**Pocket feed, second card focused**
- `{Title}`
- `Source {Source}`
- `2 of {n}`
- `Link`

_Example_

<img width="328" alt="screen shot 2018-04-19 at 12 49 30 pm" src="https://user-images.githubusercontent.com/1721875/38987465-2caa1f8e-43d0-11e8-84bc-a5b2148a097f.png">

- `Recommended videos`
- `Black Jeopardy with Chadwick Boseman - SNL`
- `Source Youtube`
- `1 of 20`
- `Link`

**Comment by BrianNJones** [comment]
@aminalhazwani , for:
<<Use left and right to move between items
How should we call the items? Items, Cards, or Recommendations, or Recommended videos. Ideas?>>

Recommend:
Use left and right to move between videos

**Comment by mcomella** [comment]
For accessibility, the system actually gives us most of the directives already and we've had a lot of difficulty trying to override the Amazon a11y behavior (it's a little more predictable on Android). Currently, when the pocket feed is opened, we get:

"Recommended videos. Youtube. <title text>. 1 of 8." Thoughts:
- We can do, "Source: <source>" but I wonder if that's a good approach: it's redundant and so while it may help for the first card, it could be annoying to hear for each card, especially if it's the first thing announced (see below). We could describe the card layout, including "this is the source", in the menu button text, however, along with "Use left and right to move between videos".
- Reordering the view announcement order is non-trivial and I'm not sure it's even possible (and it's likely to break when we update the layout). Source will have to be at the top.
- The element names, like "button", are added automatically by the framework. It's non-trivial to do this in a custom way so the only easy control we have over that is to use the framework Views, like `<Button ...` (which doesn't always work for appearance reasons). That being said, unless we're introducing a component that's used everywhere, I don't think we'd want to introduce new ones: users expect consistent elements to be announced throughout the app. On the homescreen, we actually don't announce anything now: I wonder if these should be buttons.

@eeejay Do you have thoughts? @aminalhazwani Any suggested revisions?

**Comment by lime124** [comment]
@mcomella @aminalhazwani @BrianNJones - I'm a bit fuzzy on the state of the strings. Looking at the first comment of #759 there doesn't seem to be many and it doesn't seem like there are any from the feed page. What is left and what do we need to do to finalize them?

**Comment by mcomella** [comment]
afaik, we have all the final Strings, except for:
1) The a11y strings we're talking about above
2) The Pocket tutorial overlay, but I'm not sure we we'll have time to do that (thanks Tif for pointing this out via Slack)

@aminalhazwani @BrianNJones Are the strings finalized for the Pocket tutorial overlay?

This is assuming the Pocket team likes our design and doesn't want to change it.

**Comment by aminalhazwani** [comment]
> As imperfect as it is, I think it is consistent with what users expect (for example the "button" misnomer)

I agree @eeejay

> Unless all items have the same source, I think adding it would be a good idea. It keeps it consistent with the visible information.

@eeejay afaik all items are coming from youtube, @mcomella can you confirm?

> Are the strings finalized for the Pocket tutorial overlay?

@mcomella yes, I added them here https://github.com/mozilla-mobile/firefox-tv/issues/759#issue-311393555

> The language could be more casual though, something like `{Title} on {Source}` (eg. `Black Jeopardy with Chadwick Boseman - SNL on Youtube`)

I really like this @eeejay but I don't think it's possible as @mcomella points out 

> Reordering the view announcement order is non-trivial and I'm not sure it's even possible (and it's likely to break when we update the layout). Source will have to be at the top.

For the first version I am happy with what the Fire TV gives us by default

> `Recommended videos. Youtube. <title text>. 1 of 8.`

plus the `Use left and right to move between videos` when Menu button is pressed with VoiceView enable.

If it looks good @BrianNJones feel free to add the confirmed strings to https://github.com/mozilla-mobile/firefox-tv/issues/759#issue-311393555

**Comment by mcomella** [comment]
> @eeejay afaik all items are coming from youtube, @mcomella can you confirm?

They also come from Vimeo, but very infrequently – we're talking with Pocket to make them come from more sources (you can follow along in email on firefox-tv@).

> The language could be more casual though, something like {Title} on {Source}

I actually figured out a way to do this (mute one of the announcements and override the other with a dynamically generated string). I'll try to get it in.

---

While getting the strings together for export (early landing since the features aren't done yet), I noticed:
- I don't think we finalized the strings for the error handling screen: "Something went wrong while loading the feed." @BrianNJones Do you have suggestions? I'm not sure they'll make it in this revision though (I added the strings in the mock in the comments above)
- We don't have an error state for if the Pocket tile fails to load on the homescreen @aminalhazwani ?

I should have done this yesterday, the day before they were due, so sorry about that.

---

The strings I'm currently exporting are listed here: https://github.com/mozilla-mobile/firefox-tv/pull/856

Please have a look-over to make sure I got it all right!

**Comment by aminalhazwani** [comment]
> I don't think we finalized the strings for the error handling screen: "Something went wrong while loading the feed."

@mcomella we do have the strings, see https://github.com/mozilla-mobile/firefox-tv/issues/769#issuecomment-382025170, I added them in the mock too. And now to https://github.com/mozilla-mobile/firefox-tv/issues/759#issue-311393555 as well, apologies for not updating the comment.

> We don't have an error state for if the Pocket tile fails to load on the homescreen @aminalhazwani ?

If there's an error in the homescreen, what's missing? Only the video thumbs or the whole mega tile? Also, how does the megatile load? Do we place the red rectangle/logo and then load the thumbs inside it or is it loaded all together? 

If we load all together we could use the same solution as the one we use in the pocket feed. So description plus button. And we could place them instead of the megatile. I am assuming that if everything is loaded together no thumbs/error equal no megatile. Example below (description and button need to be reviewed by @BrianNJones)

<img width="1037" alt="screen shot 2018-04-26 at 4 58 29 pm" src="https://user-images.githubusercontent.com/1721875/39313803-2a9e7dc2-4973-11e8-9026-93bc07598845.png">

If we don't load everything together, so if the thumbs are lazy loaded so to say, and there's an error, can we write something inside the megatile background? If yes, do we have control over the focus? So can we focus the "Try again" button instead of focusing the tile? Thanks!

**Comment by mcomella** [comment]
Let's move the error handling discussion to #759.

**Comment by mcomella** [comment]
I think the strings from https://github.com/mozilla-mobile/firefox-tv/issues/769#issuecomment-382025170 aren't actually contextually accurate: we're looking for a string when the feed fails to load – when the video fails to load, it's in the normal web browser context and uses the information there. Here are the strings we have:

> String for error displayed above. I think (?) users will understand that feed = video, but it can't hurt to be as plain as possible:
[Error msg]
Whoops. Something went wrong while the video was loading.
[Button]
Try again

And I think I missed this question:
> @mcomella, do we envision a scenario where the feed totally fails to load, even after user tries reloading? If so, we'll need an emsg for that.

Yes: see above. I think it'd probably be fine to just keep showing the same error message though...

**Comment by BrianNJones** [comment]
@mcomella , don't think it makes user sense to differentiate between "video" and "video feed."

[Error msg]
Sorry. We're having trouble playing that video right now.
[Button]
Try again

**Comment by BrianNJones** [comment]
@mcomella , don't think it makes user sense to differentiate between "video" and "video feed."

[Error msg]
Sorry. We're having trouble playing that video right now.
[Button]
Try again

**Comment by mcomella** [comment]
> Sorry. We're having trouble playing that video right now.

@BrianNJones This doesn't make sense to me since we're not playing any videos and we only display video thumbnails. Do you want to jump on vidyo to discuss?

**Comment by BrianNJones** [comment]
@mcomella, thanks for the vidyo explanation! this should work for both scenarios:

[Error msg]
Hmm. We're having trouble displaying video recommendations by Pocket.
[Button]
Try again

**Comment by mcomella** [comment]
We got all the strings in so unassigning us. All that's left is to get the screenshots, which appears to happen after we import.

**Comment by mcomella** [comment]
Actually, let's close this and open a new bug for screenshots to better track progress.
